# Generated by Django 4.2.2 on 2023-08-10 12:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='default_profile_image.png', upload_to=account.models.get_profile_image_path),
        ),
    ]
